export const toursAndDrivers = [
  { TOUR: "29BL", DRIVER: "Cabdirisaq Maxamed Adan" },
  { TOUR: "29C", DRIVER: "Abdullah Kawa" },
  { TOUR: "29C", DRIVER: "Adnand Mustafa" },
  { TOUR: "29L", DRIVER: "Xamse Cismaacill Yasin" },
  { TOUR: "29", DRIVER: "Sadeka Ghassan" },
  { TOUR: "29GL", DRIVER: "Samatar Mohamed" },
  { TOUR: "3910L", DRIVER: "Abdullah Ygit" },
  { TOUR: "3918", DRIVER: "Enver Shenari" },
  { TOUR: "3992", DRIVER: "Muhydhin Abdikhani" },
  { TOUR: "3992", DRIVER: "Avdi Avdiu" },
  { TOUR: "3992", DRIVER: "Tamim Salem" },
  { TOUR: "3906", DRIVER: "Enver Shenari" },
  { TOUR: "2", DRIVER: "Muhydhin Abdikhani" },
  { TOUR: "2", DRIVER: "Abdullah Kawa" },
  { TOUR: "2", DRIVER: "Adnand Mustafa" },
  { TOUR: "3&L", DRIVER: "Mohamed Bare" },
  { TOUR: "3&L", DRIVER: "Ali Osman" },
  { TOUR: "3&L", DRIVER: "Baki Adra" },
  { TOUR: "48L", DRIVER: "Abdullah Kawa" },
  { TOUR: "3906", DRIVER: "Tamim Salem" },
  { TOUR: "700", DRIVER: "Kouhsar Bahrami" },
  { TOUR: "701", DRIVER: "Firat Celik" },
  { TOUR: "702", DRIVER: "Denis" },
  { TOUR: "703", DRIVER: "Adnand Mustafa" },
  { TOUR: "703", DRIVER: "Baris Karakus" },
  { TOUR: "703", DRIVER: "Benginar Ince" },
  { TOUR: "710", DRIVER: "Tamim Salem" },
  { TOUR: "710", DRIVER: "Baris Karakus" },
  { TOUR: "D730", DRIVER: "Muhydhin Abdikhani" },
  { TOUR: "3954", DRIVER: "Abdullah Kawa" },
  { TOUR: "730", DRIVER: "Besnik Buci" },
  { TOUR: "731", DRIVER: "Jawid Faizi" },
  { TOUR: "732", DRIVER: "Nejat Rama" },
  { TOUR: "732", DRIVER: "Jawid Faizi" },
  { TOUR: "733", DRIVER: "Baris Karakus" },
  { TOUR: "733", DRIVER: "Muhydhin Abdikhani" },
  { TOUR: "Garage", DRIVER: "Massod Noori" },
];
