export const fahrer = [
  "Cabdirisaq Maxamed Adan",
  "Abdullah Kawa",
  "Adnand Mustafa",
  "Xamse Cismaciil Yasin",
  "Sadeka Ghassan",
  "Samatar Mohamed",
  "Abdulbari Ygit",
  "Enver Shenari",
  "Muhydin Abdikhani",
  "Avdi Aviu",
  "Tamim Salem",
  "Mohamed Bare",
  "Ali Osman",
  "Baki Adra",
  "Kouhsar Bahrami",
  "Firat Celik",
  "Denis",
  "Baris Karakus",
  "Benginar Ince",
  "Besnik Buci",
  "Jawid Faizi",
  "Negjat Rama",
  "Massod Noori",
];
